[package]
name = "fuzz_kernel"
version = "0.1.0"
authors = ["Polly Nielsen Boutet-Livoff <pollyboutet@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]
rlibc = "1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"
